name: 'install-pinned/mypy'
description: 'Securely install the latest mypy release from PyPI'
branding:
  icon: 'lock'
  color: 'green'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: python3 -m pip install -r $GITHUB_ACTION_PATH/requirements.txt
